### ISSUE TITLE
persistence likely doesn't properly distinguish between keywords and strings

### ISSUE THREAD

**Issue by flosell** [SimonMonecke/lambdacd-mongodb#1]
lambdacd-mongodb might be affected by the same problems the default persistence mechanism was facing (flosell/lambdacd#101), resulting in flosell/lambdacd-git#8. 

Long story short: Serializing step-results as JSON causes problems because JSON does not distinguish between keywords and strings. 

lambdacd-mongodb (like the default implementation until now) solves this issue by keywordizing all keys in a map (and probably not caring about keywords as values) (https://github.com/SimonMonecke/lambdacd-mongodb/blob/master/src/lambdacd_mongodb/mongodb_persistence.clj#L128).

This more or less works unless code tries to process old step result-data (like lambdacd-git does it to find refs it saw before), assuming keywords are keywords and strings are strings.

**Comment by SimonMonecke** [comment]
Fixed with 6374cec20a70aa8acabec4e379f8db27ab2111db by adding the prefix ":" to keywords string representation.
I did not test it with your special case. But I will do it tommorrow and close this issue if it works as expected.

**Comment by SimonMonecke** [comment]
Closed after testing the commit with a complex pipeline.
Feel free to reopen this issue, if you find a case that is not handled by this solution.
